[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "strangebasisdevs"
name = "VacationPlanner"
description = "Vote on biomes in the lobby."
websiteUrl = "" # TODO: Add a link to your mod repository here (optional)
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/VacationPlanner/release/com.github.strangebasis.VacationPlanner.dll"
target = "/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "./art/kiosk_texture.png"
target = "/kiosk_texture.png"

[[build.copy]]
source = "./art/roots_alpine_sign.png"
target = "/roots_alpine_sign.png"

[[build.copy]]
source = "./art/roots_mesa_sign.png"
target = "/roots_mesa_sign.png"

[[build.copy]]
source = "./art/tropics_alpine_sign.png"
target = "/tropics_alpine_sign.png"

[[build.copy]]
source = "./art/tropics_mesa_sign.png"
target = "/tropics_mesa_sign.png"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
